id: PFC880794
initial_creation_type: input
source_metadata:
  title: Tsele Natsok Rangdrol Series
  language: en
  description: 'Texts by Tsele Natsok Rangdrol (rtse le sna tshogs rang grol, b. 1608):'
  volume:
    c40b98391c704647a816c0cc58bddad7:
      title: 'Sweet Droplets of the Honey of Accomplishment: A Concise Explanation
        of the Indispensable Points of the Feast-Gathering'
      parent: Commentaries
created_at: '2022-03-01T01:55:10.312063'
last_modified_at: '2022-03-01T01:55:10.312069'
